### PR TITLE
Bugfix/samples to json

### PR DESCRIPTION
**Pull request by konvulse**

### CODE REVIEW

**Comment by ConduceSoftware** [comment]
Can one of the admins verify this patch?

**Comment by ConduceSoftware** [comment]
Can one of the admins verify this patch?

**Comment by ConduceSoftware** [comment]
Can one of the admins verify this patch?

**Comment by konvulse** [comment]
add to whitelist

**Comment by konvulse** [comment]
ok to test

**Comment by konvulse** [comment]
ok to test

**Comment by ConduceSoftware** [comment]
Can one of the admins verify this patch?

**Comment by konvulse** [comment]
ok to test

**Comment by konvulse** [comment]
retest this please

**Comment by konvulse** [comment]
retest this please

**Comment by konvulse** [comment]
retest this please

**Comment by konvulse** [comment]
retest this please

**Comment by konvulse** [comment]
retest this please

**Comment by konvulse** [comment]
retest this please

**Comment by konvulse** [comment]
retest this please

**Pull request closed without merging**
